version: '3.8'

services:
  # Django service
  django:
    build: .
    container_name: django-app
    networks:
      - bank_transaction_network
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=bank_db
      - DB_USER=postgres_user
      - DB_PASS=postgres_password
    volumes:
      - .:/app
    depends_on:
      - postgres-db
    command: python manage.py runserver 0.0.0.0:8000

  # PostgreSQL service
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    networks:
      - bank_transaction_network
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Jenkins service
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
      - bank_transaction_network
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - django

networks:
  bank_transaction_network:
    driver: bridge

volumes:
  postgres_data:
  jenkins_home:
